package docuconf

import (
	"github.com/stretchr/testify/require"
	"os"
	"testing"
)

func TestMyConfCompleteOutput(t *testing.T) {
	result, err := NewConfBuilder("configuration").
		AddString("SomeField", "Some Description", false, "").
		Execute()
	require.Nil(t, err)
	expected := `// Code generated by docuconf. DO NOT EDIT.
package configuration

type Configuration struct {
  SomeField string // Some Description
}
`
	goCodeFile := result.GoFiles[0]
	markDownFile := result.MarkDownFiles[0]
	require.Equal(t, expected, goCodeFile.Content)
	require.Nil(t, os.WriteFile(goCodeFile.Path, []byte(goCodeFile.Content), 0644))
	require.Nil(t, os.WriteFile(markDownFile.Path, []byte(markDownFile.Content), 0644))
}

func TestAddStringNotEnoughDescription(t *testing.T) {
	require.PanicsWithErrorf(t, "AddString(SomeField, ) Failed: description must be at least 5 characters long. This is to ensure your configuration is well documented", func() {
		NewConfBuilder("configuration").AddString("SomeField", "", true, "")
	}, "The code did not panic with the correct message")
}
